---
- hosts: All
  vars_files:
    - host_vars/vars.yaml
  gather_facts: true

  roles:
    - role: proxy
    - role: environment
    - role: mount-volumes
    - role: docker
    - role: docker_swarm
    - role: couchdb
    - role: uploader
    - role: frontmap
