################## Setup all needed environments include packages etc. ##################
################## Install dependencies on the host ##################
- name: Install pip
  become: yes
  apt:
    name: ['python3-pip']
    state: latest
    update_cache: yes
  when: ansible_distribution == "Ubuntu"
# sudo apt-get update; sudo apt-get install python-pip


- name: Update pip
  become: yes
  pip:
    name: ['pip']
    state: latest
# pip install --upgrade pip

#- name: Update and upgrade apt packages
#  become: yes
#  apt:
#    upgrade: yes
#    update_cache: yes
    # cache_valid_time: 86400 #One day




- name: Install others
  become: yes
  apt:
    name: ['python3-setuptools', 'git', 'vim', 'apt-transport-https', 'ca-certificates', 'curl', 'gnupg', 'lsb-release', 'software-properties-common', 'xfsprogs']
    state: latest 
    update_cache: yes
    install_recommends: no
