################## Common vars ##################
# Prerequisites variables.
instance_flavor: uom.mse.1c4g
availability_zone: melbourne-qh2-uom
instance_image: f8b79936-6616-4a22-b55d-0d0a1d27bceb # Ubuntu 20
instance_network: qh2-uom-internal
instance_key_name: grp-33
proxy: http://wwwproxy.unimelb.edu.au:8000/
noproxy: localhost,127.0.0.1,localaddress,172.16.0.0/12,.melbourne.rc.nectar.org.au,.storage.u nimelb.edu.au,.cloud.unimelb.edu.au

################## Volume ##################
# For each instance, define the volume size.
volumes:
  - vol_name: volume1
    vol_size: 50
    device: /dev/vdb
    mountpoint: couchdb
  - vol_name: volume2
    vol_size: 50
    device: /dev/vdb
    mountpoint: couchdb
  - vol_name: volume3
    vol_size: 50
    device: /dev/vdb
    mountpoint: couchdb
  - vol_name: volume4
    vol_size: 50
    device: /dev/vdb
    mountpoint: couchdb

################## Security group ##################
security_groups:
  - name: grp_33_ssh
    description: "Security group for SSH access"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
  - name: grp_33_http
    description: "Security group for HTTP"
    protocol: tcp
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0
  - name: grp_33_couchdb_5984
    description: "Security group for CouchDB 5984"
    protocol: tcp
    port_range_min: 5984
    port_range_max: 5984
    remote_ip_prefix: 0.0.0.0/0
  - name: grp_33_couchdb_5986
    description: "Security group for CouchDB 5986"
    protocol: tcp
    port_range_min: 5986
    port_range_max: 5986
    remote_ip_prefix: 0.0.0.0/0 
  - name: grp_33_couchdb_4369
    description: "Security group for CouchDB 4369"
    protocol: tcp
    port_range_min: 4369
    port_range_max: 4369
    remote_ip_prefix: 0.0.0.0/0
  - name: grp_33_couchdb_9100-9200
    description: "Security group for CouchDB 9100-9200"
    protocol: tcp
    port_range_min: 9100
    port_range_max: 9200
    remote_ip_prefix: 0.0.0.0/0
  - name: grp_33_frontmap
    description: "Security group for frontmap "
    protocol: tcp
    port_range_min: 3000
    port_range_max: 3000
    remote_ip_prefix: 0.0.0.0/0
  - name: grp_33_https
    description: "Security group for streamer "
    protocol: tcp
    port_range_min: 443
    port_range_max: 443
    remote_ip_prefix: 0.0.0.0/0
  - name: grp_33_swarm
    description: "Security group for docker swarm"
    protocol: tcp
    port_range_min: 2377
    port_range_max: 2377
    remote_ip_prefix: 0.0.0.0/0
  - name: grp_33_swarm_discovery
    description: "Security group for swarm container network discovery."
    protocol: tcp
    port_range_min: 7946
    port_range_max: 7946
    remote_ip_prefix: 0.0.0.0/0
  - name: grp_33_swarm_ingress
    description: "Security group for the swarm container ingress network."
    protocol: udp
    port_range_min: 4789
    port_range_max: 4789
    remote_ip_prefix: 0.0.0.0/0
################## Instance ##################
instances:
  - name: instance_1
    volumes: ['volume1']
  - name: instance_2
    volumes: ['volume2']
  - name: instance_3
    volumes: ['volume3']
  - name: instance_4
    volumes: ['volume4']


################## Setup ##################
# CouchDB
couch_user: admin
couch_password: admin
couch_version: ibmcom/couchdb3:3.0.0
couch_cookie: a192aeb9904e6590849337933b000c99
couch_data: couchdb
couch_dir: "/root/couchdir"
couch_num_shards: 8
couch_num_replicas: 4
