- name: store master ip address for later clustering
  set_fact:
    master_instance: "{{ groups['instance_1'][0] }}"

- name: create docker network which includes couchdbnode
  become: yes
  docker_network:
    name: ccc_docker_network
    connected:
      - couchdbnode
    appends: yes

# - name: create couch directory
#   become: yes
#   file:
#     path: "{{ couch_dir }}"
#     recurse: yes
#     state: directory
#     owner: "{{ ansible_user }}"
#     group: "{{ ansible_user }}"

#- name: show the groups the host(s) are in
#  debug:
#    msg: "{{ group_names }} | select('search','instance') | list | count > 0"
#    msg: 
#  when: group_names is search("instance")
#  with_items: "{{ group_names }}"
- name: copy uploader docker-compose to couchdir
  become: yes
  copy:
    src: docker-compose.yaml
    dest: "{{ couch_dir }}/docker-compose.yaml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: upload Aurin data by docker_compose
  become: yes
  docker_compose:
    project_src: "{{ couch_dir }}"
    pull: yes
    state: present
  when: ansible_host == master_instance

##- name: upload Aurin data by docker_container
#  become: yes
#  docker_container:
#    name: datauploader
#    image: liam1018/datauploader-planb
#    state: started
#  when: ansible_host == master_instance

#- name: upload by shell
#  become: yes
#  shell: "sudo docker run liam1018/datauploader-planb"
#  when: ansible_host == master_instance
