- name: copy twitter harvester docker-compose to couchdir
  become: yes
  template:
    src: docker-compose.yaml.j2
    dest: "{{ couch_dir }}/docker-compose.yaml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: deploy twitter harvester by docker_compose
  become: yes
  docker_compose:
    project_src: "{{ couch_dir }}"
    pull: yes
    state: present

