- name: store master ip address for later use
  set_fact:
    master_instance: "{{ groups['instance_1'][0] }}"

#- name: copy frontmap docker-compose to couchdir
#  become: yes
#  copy:
#    src: docker-compose.yaml
#    dest: "{{ couch_dir }}/docker-compose.yaml"
#    owner: "{{ ansible_user }}"
#    group: "{{ ansible_user }}"
#
#- name: deploy frontmap by docker-compose
#  become: yes
#  docker_compose:
#    project_src: "{{ couch_dir }}"
#    pull: yes
#    state: present
#  when: ansible_host == master_instance
- name: deploy frontmap by docker service
  become: yes
  docker_swarm_service:
    name: frontmap
    image: liam1018/map526.1
    replicas: 3
    publish:
      - published_port: 3000
        target_port: 3000
  when: ansible_host == master_instance
