version: "3.7"

services:
  frontmap:
#    depends_on:
#      - couchdbnode
    image: liam1018/frontmap
    ports: 
      - "3000:3000"
#  twitterharvester:
#    image: liam1018/twitterharvester2

    
networks:
  default:
    external: true
    name: ccc_docker_network
