# Proxy for instances.
- name: Proxy 
  become: yes
  blockinfile:
    path: /etc/environment
    block: |
      HTTP_PROXY={{ proxy }} 
      HTTPS_PROXY={{ proxy }}
      http_proxy={{ proxy }}
      https_proxy={{ proxy }}
      no_proxy={{ noproxy }}
  
- name: Reboot
  become: yes
  reboot:
    reboot_timeout: 500